### ISSUE TITLE
Determine how to handle special characters in field names

### ISSUE THREAD

**Issue by byronhulcher** [elastic/app-search-firestore-extension#16]
- [ ] `,` comma characters (they break our splitting logic)
- [ ] `.` period characters (they break our nested field logic)
- [ ] Non-english/alphanumeric UTF-8 characters (ie field names like `网址` and `图片`, which translate to URL and image from Chinese)

We could handle these in our code, or alternatively write a note in our documentation and/or config.

**Comment by JasonStoltz** [comment]
My proposal.

Continue to split on `,`, it is what it is, I highly doubt anyone uses commas in their field names.

Change the `.` syntax to `__` syntax for specifying nested fields. *Always* first look for the literal `field__subfield` field to see if it exists first, and use that literally if it does. If it does not, they parse it and look for the matching subfield.

Ditto for `::`, allow users to specify a new name for their field with `::`, but look for the literal field with `::` in it first.

Use a regex to remove anything other than alpha numeric or '_' before sending to App Search.
